name: 'Destroy EC2, RDS and Route53'

on:
  workflow_dispatch: 

env:
  BUCKET_NAME: "my-terraform-state-805714761459"
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/auto-scaling-ec2-waf-53-rds
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::805714761459:role/aws-deployment-tf
          role-session-name: destroy-session

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.6

      - name: Terraform Init
        run: |
                  terraform init \
                    -backend-config="bucket=${{ env.BUCKET_NAME }}" \
                    -backend-config="region=${{ env.AWS_REGION }}" \
                    -backend-config="key=staging/terraform.tfstate"

      - name: Force Clean Route53 Records
        run: |
          ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "app.salvador.com." --query "HostedZones[0].Id" --output text | cut -d'/' -f3)
          if [ "$ZONE_ID" != "None" ] && [ -n "$ZONE_ID" ]; then
            echo "Limpando registros da zona $ZONE_ID..."
            # Lista todos os registros que não são NS ou SOA e gera o batch de DELETE
            aws route53 list-resource-record-sets --hosted-zone-id $ZONE_ID --query "ResourceRecordSets[?Type != 'NS' && Type != 'SOA']" | jq '{Changes: [.[] | {Action: "DELETE", ResourceRecordSet: .}]}' > batch.json
            
            if [ $(jq '.Changes | length' batch.json) -gt 0 ]; then
              aws route53 change-resource-record-sets --hosted-zone-id $ZONE_ID --change-batch file://batch.json
              sleep 10
            fi
          fi

      - name: Terraform Destroy
        run: terraform destroy --auto-approve --var-file=staging.terraform.tfvars
        
