name: 'Create EC2, RDS and Route53'

on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read 
env: 
  AWS_REGION: us-east-1 
  TF_VERSION: 1.2.6   
  BUCKET_NAME: "my-terraform-state-805714761459"

jobs:
  terraform:
    name: infrastructure-staging
    runs-on: ubuntu-latest
    timeout-minutes: 30

    defaults:
      run:
        shell: bash

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::805714761459:role/aws-deployment-tf
        role-session-name: staging-session    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}      

    - name: Terraform Init
      working-directory: ./terraform/auto-scaling-ec2-waf-53-rds
      run: |
          terraform init \
            -backend-config="bucket=${{ env.BUCKET_NAME }}" \
            -backend-config="key=staging/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

    - name: Terraform Validate
      working-directory: ./terraform/auto-scaling-ec2-waf-53-rds
      run: terraform validate -no-color    

    - name: Terraform Plan
      working-directory: ./terraform/auto-scaling-ec2-waf-53-rds
      run: terraform plan --var-file=staging.terraform.tfvars  

    - name: Terraform Apply
      working-directory: ./terraform/auto-scaling-ec2-waf-53-rds
      run: terraform apply --auto-approve --var-file=staging.terraform.tfvars

 
      
